name:                app-backend-h
version:             0.1.0.0
github:              "githubuser/app-backend-h"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/app-backend-h#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.3.1.1 && < 1.4
- lens-aeson >= 1.0.2 && < 1.1
- postgresql-simple >= 0.5.4.0 && < 0.6
- text >= 1.2.3.1 && < 1.3
- time >= 1.8.0.2 && < 1.9
- uuid >= 1.3.13 && < 1.4

library:
  source-dirs: src
  default-extensions: DeriveGeneric
                    , OverloadedStrings

executables:
  app-backend-h-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - app-backend-h

tests:
  app-backend-h-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - app-backend-h
